version: '3.9'
services:
  database:
    image: postgres
    ports:
      - 5432:5432
    env_file: 
      - ./.env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - ./database-schema/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - test
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  auth:
    build: ./auth-golang
    ports:
      - 5002:5002
    depends_on:
      database:
        condition: service_healthy
    networks:
      test:
        ipv4_address: 10.5.0.4

  neural:
    build: ./neural
    ports:
      - 5010:5010
    networks:
      test:
        ipv4_address: 10.5.0.5

  parser:
    build: ./parser-golang
    ports:
      - 5008:5008
    networks:
      test:
        ipv4_address: 10.5.0.6

  front-react:
    build: ./front-react
    ports:
      - 3000:3000
    networks:
      test:
        ipv4_address: 10.5.0.7

networks:
  test:
    name: test
    external: false
    ipam:
      config:
        - subnet: 10.5.0.0/16
          gateway: 10.5.0.1